file = open("sample.txt", "w")
file.write("Hello Python\n")
file.write("Welcome to File Handling\n")
file.close()
file = open("sample.txt", "r")
print("Original Data:")
print(file.read())
file.close()
file = open("sample.txt", "a")
file.write("This is new data\n")
file.close()
file = open("sample.txt", "r")
print("After Appending:")
print(file.read())
file.close()